"$schema" = 'https://starship.rs/config-schema.json'


[line_break]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[username]
style_user = "bold blue"
format = "[$user]($style)[/](bold)"

[hostname]
format ="[$ssh_symbol$hostname]($style): "
style= "bold fg:purple"

[directory]
style = "bold #00ffff"
truncation_length = 100

[git_branch]
format = "[git:](bold #0073ff)[$branch(:$remote_branch)]($style) " 
style = "bold red"

[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style) )'

[package]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[python]
format = '[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[scala]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[java]
disabled = true
