vim.keymap.set("n", "<leader>dd", ":lua require'dap'.continue()<CR>")
vim.keymap.set("n", "<leader>dq", ":lua require'dap'.terminate()<CR>")
vim.keymap.set("n", "<leader>dl", ":lua require'dap'.step_into()<CR>")
vim.keymap.set("n", "<leader>dj", ":lua require'dap'.step_over()<CR>")
vim.keymap.set("n", "<leader>dk", ":lua require'dap'.step_out()<CR>")
vim.keymap.set("n", "<leader>dr", ":lua require'dap'.repl.open()<CR>")
vim.keymap.set("n", "<leader>d<space>", ":lua require('dapui').toggle()<CR>")
vim.keymap.set("n", "<leader>db", ":lua require'dap'.toggle_breakpoint()")
