require("config.set")
require("config.keymap")
require("config.netrw")
require("config.lsp")
require("config.treesitter")
require("config.autocommands")
require("config.usercommands")
require("config.colourscheme")
require("config.luasnip")
require("config.neotest")

