require("config.set")
require("config.keymap")
require("config.netrw")
require("config.telescope")
require("config.lsp")
require("config.dap")
require("config.treesitter")
require("config.neotest")
require("config.autocommands")
require("config.usercommands")
require("config.colourscheme")
require("config.luasnip")
require("config.indent_blankline")

