#!/bin/bash


OPT=$(echo -e "context\ntoggle\nclear\nclear-all\npop\nstatus\ncancel" | bemenu -l 8 --binding vim -p "Dunst Paused? : $(dunstctl is-paused)")

case $OPT in
        # Lock-Screen) betterlockscreen -l -t "Enter Your Password";;
        context) dunstctl context;;
        toggle) dunstctl set-paused toggle;;
        clear) dunstctl close;;
        clear-all) dunstctl close-all;;
        pop) dunstctl history-pop;;
        status) notify-send "$(dunstctl count)";;
        *) ;; 
esac 

signal-waybar
