#!/bin/bash

OPT=$(echo -e "Left\nRight\nCancel" | dmenu -i -l 4 -c -bw 4 -p "Select a monitor to record")

case $OPT in
Left) ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0+0,0 output.mp4 ;;
Right) ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0+1920,0 output.mp4 ;;
*) ;;
esac
