#!/bin/bash
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=gtk3
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export GTK_THEME=Adwaita:dark
export MOZ_ENABLE_WAYLAND=1

XDG_CURRENT_DESKTOP=sway
exec sway
