#!/bin/bash

OPT=$(echo -e "Cancel\nLock-Screen\nReload-Sway\nExit-Sway\nSuspend\nReboot\nShutdown" | bemenu -i -l 7 -I 1--binding vim -p "Power Options:")

case $OPT in
Lock-Screen) swaylock ;;
Reload-Sway) swaymsg reload ;;
Exit-Sway) swaymsg exit ;;
Suspend) systemctl suspend ;;
Reboot) reboot ;;
Shutdown) shutdown now ;;
*) ;;
esac
