#!/bin/sh

#Buttons on Tablet
xsetwacom set "Wacom Intuos BT S Pad pad" Button 1 "key ctrl shift g"
xsetwacom set "Wacom Intuos BT S Pad pad" Button 2 "key ctrl shift p"

#Cursor speed reduce
xinput -set-prop 'Wacom Intuos BT S Pen stylus' 'Device Accel Constant Deceleration' 3.5
xsetwacom set 'Wacom Intuos BT S Pen stylus' Mode Relative

