#!/bin/sh

zoomlinks(){
    
    url=`cat ~/.scripts/zoom-launch/links.txt | dmenu -l 20 | awk '{print $2}'`
    org=$(echo $url | awk  -F/ '{print $3}') 
    meeting=$(echo $url | awk -F/ '{print $5}' | sed 's/?/\&/g')
    echo "zoommtg://$org/join?action=join&confno=$meeting" | xargs xdg-open
}

zoomlinks
